version: '3.8'

services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "${WPBP_MYSQL_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: ${WP_CONFIG_EXTRA}
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content:rw
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    ports:
      - "${WP_MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  wordpress:
  db-data:
